spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://localhost:5433/f1_notification_db
    username: f1user
    password: f1pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: notification-service-group
      auto-offset-reset: latest
  mail:
    host: ${SMTP_HOST:smtp.gmail.com}
    port: ${SMTP_PORT:587}
    username: ${SMTP_USERNAME:}
    password: ${SMTP_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8087

kafka:
  topics:
    notifications: f1.notifications
    race-events: f1.events.race
    alerts: f1.alerts

logging:
  level:
    com.example.f1notificationservice: INFO