spring:
  application:
    name: timing-service
  datasource:
    url: jdbc:postgresql://localhost:5433/f1_timing_db
    username: f1user
    password: f1pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterWrite=5m
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8083

# OpenF1 API
openf1:
  base-url: https://api.openf1.org/v1
  timeout-seconds: 10

# Session Service (Feign Client için)
session-service:
  url: http://localhost:8082

# Resilience4j
resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 30s
        permittedNumberOfCallsInHalfOpenState: 3
    instances:
      openf1:
        baseConfig: default

logging:
  level:
    com.example.f1timingservice: INFO
